-- Per-course completion records (run after supabase-elearning-courses.sql).

create table if not exists public.elearning_completions (
  id             bigint generated by default as identity primary key,
  learner_id     bigint not null references public.learners (id) on delete cascade,
  course_id      bigint not null references public.elearning_courses (id) on delete cascade,
  completed_at   timestamptz not null default now(),
  unique (learner_id, course_id)
);

create index if not exists elearning_completions_learner_idx
  on public.elearning_completions (learner_id);

create index if not exists elearning_completions_course_idx
  on public.elearning_completions (course_id);

alter table public.elearning_completions enable row level security;

-- Backfill from legacy learners.completed_at (assigned course slug → course row).
insert into public.elearning_completions (learner_id, course_id, completed_at)
select l.id, c.id, l.completed_at
from public.learners l
join public.elearning_courses c on c.slug = l.course_slug
where l.completed_at is not null
on conflict (learner_id, course_id) do nothing;
