-- Multi-course e-learning + learner admin (run after supabase-schema.sql &
-- optionally after supabase-elearning-admin.sql).

create table if not exists public.elearning_courses (
  id                     bigint generated by default as identity primary key,
  slug                   text not null unique,
  title                  text not null,
  tagline                text not null default '',
  duration               text not null default '',
  entry_file             text not null default 'index.html',
  storage_prefix         text,
  sort_order             int not null default 0,
  assign_on_lead         boolean not null default false,
  is_catalog_teaser      boolean not null default false,
  is_open_to_all_learners boolean not null default false,
  tag                    text not null default 'Course',
  accent_class           text not null default 'from-[#016068] to-[#024850]',
  icon_path              text not null default 'M12 2 4 5v6c0 5 3.5 9.5 8 11 4.5-1.5 8-6 8-11V5l-8-3Z',
  package_updated_at     timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- At most one course may be designated for Zapier / lead-form assignment.
create unique index if not exists elearning_courses_one_assign_on_lead
  on public.elearning_courses ((true))
  where assign_on_lead is true;

alter table public.elearning_courses enable row level security;

-- Migrate legacy singleton (if present) — run once.
insert into public.elearning_courses (
  slug, title, tagline, duration, entry_file, storage_prefix,
  sort_order, assign_on_lead, is_catalog_teaser, is_open_to_all_learners,
  tag, accent_class, icon_path, package_updated_at
)
select
  ecs.slug,
  ecs.title,
  ecs.tagline,
  ecs.duration,
  ecs.entry_file,
  ecs.storage_prefix,
  0,
  true,
  false,
  true,
  'Free • Complimentary',
  'from-[#016068] to-[#024850]',
  'M12 2 4 5v6c0 5 3.5 9.5 8 11 4.5-1.5 8-6 8-11V5l-8-3Z',
  ecs.package_updated_at
from public.elearning_course_settings ecs
where ecs.id = 1
on conflict (slug) do nothing;

-- Fresh installs: seed default playable course when table was empty.
insert into public.elearning_courses (
  slug, title, tagline, duration, entry_file,
  sort_order, assign_on_lead, is_catalog_teaser, is_open_to_all_learners,
  tag, accent_class
)
values (
  'electrical-safety-essentials',
  'Electrical Safety Essentials',
  'A concise introduction to working safely with electricity.',
  'Approx. 30 minutes',
  'index.html',
  0,
  true,
  false,
  true,
  'Free • Complimentary',
  'from-[#016068] to-[#024850]'
)
on conflict (slug) do nothing;
