-- Learn Technique · Learner portal schema
-- Run this once in the Supabase SQL editor (Project → SQL → New query),
-- or via `supabase db push` if you use the Supabase CLI.

create table if not exists public.learners (
  id              bigint generated by default as identity primary key,
  email           text not null unique,
  first_name      text not null default '',
  last_name       text not null default '',
  phone           text,
  password_hash   text not null,
  course_slug     text not null default 'electrical-safety-essentials',
  completed_at    timestamptz,
  source          text,
  ad_campaign     text,
  created_at      timestamptz not null default now(),
  last_login_at   timestamptz
);

create index if not exists learners_email_idx
  on public.learners (lower(email));

-- Row-Level Security: lock the table so nothing can reach it from the
-- browser. Our server-side API routes use the `service_role` key, which
-- bypasses RLS — there are no anon / authenticated policies by design.
alter table public.learners enable row level security;

-- Ensure no public policies exist (defensive cleanup).
do $$
declare p record;
begin
  for p in
    select policyname from pg_policies
     where schemaname = 'public' and tablename = 'learners'
  loop
    execute format('drop policy if exists %I on public.learners', p.policyname);
  end loop;
end $$;
